Description: >

    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
    
Resources:
    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow http to our load balancer
            VpcId: !Ref VPC
            SecurityGroupIngress:
                -   IpProtocol: TCP
                    FromPort: 80
                    ToPort: 80
                    CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                -   IpProtocol: TCP
                    FromPort: 80
                    ToPort: 80
                    CidrIp: 0.0.0.0/0
            Tags: 
                - Key: Name
                  Value: !Sub ${WorkflowID}-LoadBalancerSecurityGrp

Outputs:
    LoadBalancerSecurityGroup:
        Description: Load balancer security group
        Value: !Ref LoadBalancerSecurityGroup
        Export:
            Name: !Sub ${WorkflowID}-LoadBalancerSecurityGrp
